# Generated by Django 4.1.1 on 2022-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stck", "0002_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.CharField(default="no song title", max_length=100),
        ),
        migrations.AlterField(
            model_name="song",
            name="preview_url",
            field=models.TextField(default="No Image"),
        ),
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(default="no song title", max_length=100),
        ),
    ]
