# Generated by Django 4.1.1 on 2022-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stck", "0003_alter_song_album_alter_song_preview_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyStocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_amount_of_shares", models.CharField(max_length=100)),
                ("price_prediction", models.CharField(max_length=100)),
                ("buy_or_sell", models.CharField(max_length=100)),
            ],
        ),
    ]
