# Generated by Django 4.1.1 on 2022-09-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stck", "0004_mystocks"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="artist",),
        migrations.DeleteModel(name="Artist",),
        migrations.DeleteModel(name="Song",),
    ]
